# Generated by Django 5.1 on 2025-03-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_likepost_post_id_alter_likepost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='post_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='user',
            field=models.CharField(max_length=500),
        ),
    ]
