# Generated by Django 5.1 on 2025-03-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_likepost_post_id_alter_likepost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='post_id',
            new_name='post',
        ),
    ]
