# Generated by Django 5.1 on 2025-03-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_post_id_likepost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='year_group',
            field=models.CharField(blank=True, choices=[('7', 'Year 7'), ('8', 'Year 8'), ('9', 'Year 9'), ('10', 'Year 10'), ('11', 'Year 11'), ('12', 'Year 12'), ('13', 'Year 13')], max_length=7, null=True),
        ),
    ]
