# Generated by Django 5.1 on 2025-03-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_profile_location_profile_year_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank_profile_picture.png', upload_to='profile_images'),
        ),
    ]
