# Generated by Django 5.1 on 2025-03-20 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='blank_club_profile_image', upload_to='club_profile_images')),
                ('description', models.TextField(blank=True)),
                ('club_category', models.CharField(blank=True, choices=[('Academic', 'Academic & Professional'), ('Sport', 'Sports & Recreation'), ('Arts', 'Arts & Creativity'), ('Identity', 'Culture & Identity Based'), ('Community', 'Community Service & Social Impact'), ('Interests', 'Special Interests & Hobbies'), ('Other', 'Other')], max_length=30, null=True)),
            ],
        ),
    ]
