# Generated by Django 5.1 on 2025-03-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(default='blank_club_profile_image.png', upload_to='club_profile_images'),
        ),
    ]
