# Generated by Django 5.1 on 2025-03-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(default='blank_club_profile_image.png', max_length=300, upload_to='club_profile_images'),
        ),
    ]
